server:
  port: 8099

# llmbase
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.minimaxi.com/v1
      api-key: ${MINIMAX_M2.5_LANGCHAIN}
      model-name: MiniMax-M2.5
      log-requests: true
      log-responses: true
      # ????(???)
      temperature: 0.8
      timeout: PT60S
  community:
    dashscope:
      chat-model:
        api-key: ${ALI_BAILIAN}
        model-name: qwen-plus
      embedding-model:
        api-key: sk-da76437b3ee14e2cb2d718de905152e0
        model-name: text-embedding-v4
logging:
  level:
    root: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33306/guiguxiaozhi?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/chat_memory_db?authSource=admin
